import sqlite3 as sl

def check() -> None:
    con = sl.connect('entrance.db')
    with con:
        data = con.execute("select count(*) from sqlite_master where type='table' and name='students'")
        for row in data:
            if row[0] == 0:
                with con:
                    con.execute("""
                        CREATE TABLE students (
                        ID INT PRIMARY KEY,
                        SCORE INT,
                        GAVE? BOOL,
                        WHERE NVARCHAR(100),
                        COLLEGE1 NVARCHAR(100),
                                OWN ACHIEVEMENT COLLEGE1 INT,
                                WAY COLLEGE1 NVARCHAR(100),
                                DIRECTION1 COLLEGE1 NVARCHAR(300),
                                DIRECTION2 COLLEGE1 NVARCHAR(300),
                                DIRECTION3 COLLEGE1 NVARCHAR(300),
                                DIRECTION4 COLLEGE1 NVARCHAR(300),
                                DIRECTION5 COLLEGE1 NVARCHAR(300),
                                PLACE DIRECTION1 COLLEGE1 INT,
                                PLACE DIRECTION2 COLLEGE1 INT,
                                PLACE DIRECTION3 COLLEGE1 INT,
                                PLACE DIRECTION4 COLLEGE1 INT,
                                PLACE DIRECTION5 COLLEGE1 INT,
                        COLLEGE2 NVARCHAR(100),
                                OWN ACHIEVEMENT COLLEGE2 INT,
                                WAY COLLEGE2 NVARCHAR(100),
                                DIRECTION1 COLLEGE2 NVARCHAR(300),
                                DIRECTION2 COLLEGE2 NVARCHAR(300),
                                DIRECTION3 COLLEGE2 NVARCHAR(300),
                                DIRECTION4 COLLEGE2 NVARCHAR(300),
                                DIRECTION5 COLLEGE2 NVARCHAR(300),
                                PLACE DIRECTION1 COLLEGE2 INT,
                                PLACE DIRECTION2 COLLEGE2 INT,
                                PLACE DIRECTION3 COLLEGE2 INT,
                                PLACE DIRECTION4 COLLEGE2 INT,
                                PLACE DIRECTION5 COLLEGE2 INT,
                        COLLEGE3 NVARCHAR(100),
                                OWN ACHIEVEMENT COLLEGE3 INT,
                                WAY COLLEGE3 NVARCHAR(100),
                                DIRECTION1 COLLEGE3 NVARCHAR(300),
                                DIRECTION2 COLLEGE3 NVARCHAR(300),
                                DIRECTION3 COLLEGE3 NVARCHAR(300),
                                DIRECTION4 COLLEGE3 NVARCHAR(300),
                                DIRECTION5 COLLEGE3 NVARCHAR(300),
                                PLACE DIRECTION1 COLLEGE3 INT,
                                PLACE DIRECTION2 COLLEGE3 INT,
                                PLACE DIRECTION3 COLLEGE3 INT,
                                PLACE DIRECTION4 COLLEGE3 INT,
                                PLACE DIRECTION5 COLLEGE3 INT,
                        COLLEGE4 NVARCHAR(100),
                                OWN ACHIEVEMENT COLLEGE4 INT,
                                WAY COLLEGE4 NVARCHAR(100),
                                DIRECTION1 COLLEGE4 NVARCHAR(300),
                                DIRECTION2 COLLEGE4 NVARCHAR(300),
                                DIRECTION3 COLLEGE4 NVARCHAR(300),
                                DIRECTION4 COLLEGE4 NVARCHAR(300),
                                DIRECTION5 COLLEGE4 NVARCHAR(300),
                                PLACE DIRECTION1 COLLEGE4 INT,
                                PLACE DIRECTION2 COLLEGE4 INT,
                                PLACE DIRECTION3 COLLEGE4 INT,
                                PLACE DIRECTION4 COLLEGE4 INT,
                                PLACE DIRECTION5 COLLEGE4 INT,
                        COLLEGE5 NVARCHAR(100),
                                OWN ACHIEVEMENT COLLEGE5 INT,
                                WAY COLLEGE5 NVARCHAR(100),
                                DIRECTION1 COLLEGE5 NVARCHAR(300),
                                DIRECTION2 COLLEGE5 NVARCHAR(300),
                                DIRECTION3 COLLEGE5 NVARCHAR(300),
                                DIRECTION4 COLLEGE5 NVARCHAR(300),
                                DIRECTION5 COLLEGE5 NVARCHAR(300),
                                PLACE DIRECTION1 COLLEGE5 INT,
                                PLACE DIRECTION2 COLLEGE5 INT,
                                PLACE DIRECTION3 COLLEGE5 INT,
                                PLACE DIRECTION4 COLLEGE5 INT,
                                PLACE DIRECTION5 COLLEGE5 INT
                                """)